### ISSUE TITLE
Visualization of the segmentation results codes

### ISSUE THREAD

**Issue by Eurus-Holmes** [Tencent/MedicalNet#6]
Would you release your visualization codes?

**Comment by cshwhale** [comment]
We visualized the segmentation results by ITK-SNAP software.

**Comment by Eurus-Holmes** [comment]
oh, I see, but in your code `test.py`, it seems you don't save the predicted mask images?

**Comment by pervinh** [comment]
Hi, I have the same problem too. How can i save segmentation results as nifti files?

**Comment by cshwhale** [comment]
@Eurus-Holmes 
Hi, I save the predicted mask as nii format and then visualize it with ITK-SNAP software. The code is as follows:
import nibabel
vis_data = nibabel.Nifti1Image(np.array(mask).astype(np.float32), np.eye(4))
nibabel.save(vis_data, "mask_vis.nii.gz")

**Comment by pervinh** [comment]
@cshwhale 
Thank you, this worked

**Comment by Eurus-Holmes** [comment]
@cshwhale Thanks!

**Comment by ni-wei** [comment]
> @Eurus-Holmes
> @pervinh
> Hi, I save the predicted mask as nii format and then visualize it with ITK-SNAP software. The code is as follows:
> import nibabel
> vis_data = nibabel.Nifti1Image(np.array(mask).astype(np.float32), np.eye(4))
> nibabel.save(vis_data, "mask_vis.nii.gz")

Hi,

in order to register the predicted mask with the data & label, does it make sense to obtain a "target_affine" from the data, and replace the "np.eye(4)" in SH's code with this "target_affine"?
I obtained the "target_affine" by inserting the following 2 lines next to [https://github.com/Tencent/MedicalNet/blob/25ba32573f281646f8a3d15f096d017de615ee3a/test.py#L62](url)
data = nib.load(os.path.join(sets.data_root, img_names[batch_id]))
target_affine = data.affine

Thanks,
Wei
